"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/wan/tasks"

ENDPOINTS = {
    "wan_generate_video": {
        "method": "POST",
        "path": "/wan/videos",
        "operation": "generate",
        "schema": {
            "type": "object",
            "required": ["model"],
            "properties": {
                "audio": {"type": "boolean"},
                "prompt_extend": {"type": "boolean"},
                "action": {"enum": ["text2video", "image2video"], "type": "string"},
                "resolution": {"enum": ["480P", "720P", "1080P"], "type": "string"},
                "shot_type": {"enum": ["single", "multi"], "type": "string"},
                "duration": {
                    "type": "number",
                    "oneOf": [
                        {"type": "integer", "minimum": 2, "maximum": 30},
                        {"type": "integer", "enum": [-1]},
                    ],
                },
                "prompt": {"type": "string"},
                "negative_prompt": {"type": "string"},
                "size": {"type": "string"},
                "audio_url": {"type": "string"},
                "reference_video_urls": {
                    "type": "array",
                    "minItems": 1,
                    "items": {"type": "string", "format": "uri"},
                },
                "model": {
                    "enum": [
                        "wan2.6-i2v",
                        "wan2.6-r2v",
                        "wan2.6-i2v-flash",
                        "wan2.6-t2v",
                        "wan3.0-video",
                    ],
                    "type": "string",
                },
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
                "image_url": {"type": "string"},
                "media": {
                    "type": "array",
                    "maxItems": 10,
                    "items": {
                        "type": "object",
                        "required": ["type", "url"],
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "first_frame",
                                    "last_frame",
                                    "reference_image",
                                    "reference_video",
                                    "reference_audio",
                                    "file",
                                    "link",
                                ],
                            },
                            "url": {"type": "string"},
                        },
                    },
                },
                "ratio": {
                    "type": "string",
                    "enum": ["adaptive", "16:9", "4:3", "1:1", "3:4", "9:16"],
                },
                "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
                "watermark": {"type": "boolean"},
            },
        },
        "properties": {
            "audio": {"type": "boolean"},
            "prompt_extend": {"type": "boolean"},
            "action": {"enum": ["text2video", "image2video"], "type": "string"},
            "resolution": {"enum": ["480P", "720P", "1080P"], "type": "string"},
            "shot_type": {"enum": ["single", "multi"], "type": "string"},
            "duration": {
                "type": "number",
                "oneOf": [
                    {"type": "integer", "minimum": 2, "maximum": 30},
                    {"type": "integer", "enum": [-1]},
                ],
            },
            "prompt": {"type": "string"},
            "negative_prompt": {"type": "string"},
            "size": {"type": "string"},
            "audio_url": {"type": "string"},
            "reference_video_urls": {
                "type": "array",
                "minItems": 1,
                "items": {"type": "string", "format": "uri"},
            },
            "model": {
                "enum": [
                    "wan2.6-i2v",
                    "wan2.6-r2v",
                    "wan2.6-i2v-flash",
                    "wan2.6-t2v",
                    "wan3.0-video",
                ],
                "type": "string",
            },
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
            "image_url": {"type": "string"},
            "media": {
                "type": "array",
                "maxItems": 10,
                "items": {
                    "type": "object",
                    "required": ["type", "url"],
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "first_frame",
                                "last_frame",
                                "reference_image",
                                "reference_video",
                                "reference_audio",
                                "file",
                                "link",
                            ],
                        },
                        "url": {"type": "string"},
                    },
                },
            },
            "ratio": {"type": "string", "enum": ["adaptive", "16:9", "4:3", "1:1", "3:4", "9:16"]},
            "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
            "watermark": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {
            "model": "wan2.6-t2v",
            "action": "text2video",
            "duration": 5,
            "resolution": "720P",
        },
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "wan3_generate": {
        "method": "POST",
        "path": "/wan/videos",
        "operation": "wan3",
        "schema": {
            "type": "object",
            "required": ["model"],
            "properties": {
                "audio": {"type": "boolean"},
                "prompt_extend": {"type": "boolean"},
                "action": {"enum": ["text2video", "image2video"], "type": "string"},
                "resolution": {"enum": ["480P", "720P", "1080P"], "type": "string"},
                "shot_type": {"enum": ["single", "multi"], "type": "string"},
                "duration": {
                    "type": "number",
                    "oneOf": [
                        {"type": "integer", "minimum": 2, "maximum": 30},
                        {"type": "integer", "enum": [-1]},
                    ],
                },
                "prompt": {"type": "string"},
                "negative_prompt": {"type": "string"},
                "size": {"type": "string"},
                "audio_url": {"type": "string"},
                "reference_video_urls": {
                    "type": "array",
                    "minItems": 1,
                    "items": {"type": "string", "format": "uri"},
                },
                "model": {
                    "enum": [
                        "wan2.6-i2v",
                        "wan2.6-r2v",
                        "wan2.6-i2v-flash",
                        "wan2.6-t2v",
                        "wan3.0-video",
                    ],
                    "type": "string",
                },
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
                "image_url": {"type": "string"},
                "media": {
                    "type": "array",
                    "maxItems": 10,
                    "items": {
                        "type": "object",
                        "required": ["type", "url"],
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "first_frame",
                                    "last_frame",
                                    "reference_image",
                                    "reference_video",
                                    "reference_audio",
                                    "file",
                                    "link",
                                ],
                            },
                            "url": {"type": "string"},
                        },
                    },
                },
                "ratio": {
                    "type": "string",
                    "enum": ["adaptive", "16:9", "4:3", "1:1", "3:4", "9:16"],
                },
                "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
                "watermark": {"type": "boolean"},
            },
        },
        "properties": {
            "audio": {"type": "boolean"},
            "prompt_extend": {"type": "boolean"},
            "action": {"enum": ["text2video", "image2video"], "type": "string"},
            "resolution": {"enum": ["480P", "720P", "1080P"], "type": "string"},
            "shot_type": {"enum": ["single", "multi"], "type": "string"},
            "duration": {
                "type": "number",
                "oneOf": [
                    {"type": "integer", "minimum": 2, "maximum": 30},
                    {"type": "integer", "enum": [-1]},
                ],
            },
            "prompt": {"type": "string"},
            "negative_prompt": {"type": "string"},
            "size": {"type": "string"},
            "audio_url": {"type": "string"},
            "reference_video_urls": {
                "type": "array",
                "minItems": 1,
                "items": {"type": "string", "format": "uri"},
            },
            "model": {
                "enum": [
                    "wan2.6-i2v",
                    "wan2.6-r2v",
                    "wan2.6-i2v-flash",
                    "wan2.6-t2v",
                    "wan3.0-video",
                ],
                "type": "string",
            },
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
            "image_url": {"type": "string"},
            "media": {
                "type": "array",
                "maxItems": 10,
                "items": {
                    "type": "object",
                    "required": ["type", "url"],
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "first_frame",
                                "last_frame",
                                "reference_image",
                                "reference_video",
                                "reference_audio",
                                "file",
                                "link",
                            ],
                        },
                        "url": {"type": "string"},
                    },
                },
            },
            "ratio": {"type": "string", "enum": ["adaptive", "16:9", "4:3", "1:1", "3:4", "9:16"]},
            "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
            "watermark": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {
            "model": "wan3.0-video",
            "action": "text2video",
            "duration": 5,
            "resolution": "720P",
        },
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "wan_task_retrieve": {
        "method": "POST",
        "path": "/wan/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "wan_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/wan/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
            "required": ["action", "ids"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
